labels:
  neo: "neo_raw"
  meteorites: "meteorites_raw"

unsupervised_learning:
  features:
    - est_diameter_min
    - est_diameter_max
    - relative_velocity
    - miss_distance
    - absolute_magnitude
    - diameter_mean
    - log_velocity
    - log_miss_distance
  clustering:
    scaler: standard
    kmeans:
      n_clusters: 4
      random_state: 42
    dbscan:
      eps: 0.6
      min_samples: 10
    gmm:
      n_components: 4
      covariance_type: full
      random_state: 42
  dimensionality_reduction:
    pca:
      n_components: 2
      random_state: 42
    umap:
      n_neighbors: 15
      min_dist: 0.1
      n_components: 2
      random_state: 42
  visualization:
    max_points: 3000
  cluster_feature:
    label_column: "cluster_label"